### PR TITLE
Fix controller script validation tests

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Be-ing** [comment]
I can't get the last commit to build. Could you give it a try?

**Comment by ferranlala** [comment]
Thanks! I'm closing this and merging locally. You made ControllerJSProxy::send function virtual, but it was also inline, thus this was happening: https://www.daniweb.com/programming/software-development/threads/114299/undefined-reference-to-vtable-for

**Comment by ferranlala** [comment]
Well...it turned out not to be that simple...

**Comment by ferranlala** [comment]
From the GCC FAQ: The solution is to ensure that all virtual methods that are not pure are defined.

**Comment by ferranlala** [comment]
I give up. I don't know how to fix this. I've tried making both `ControllerJSProxy::send` and `FakeControllerJSProxy::send` out-of-line but still getting the error
```
Undefined symbols for architecture x86_64:
  "vtable for FakeControllerJSProxy", referenced from:
      FakeControllerJSProxy::FakeControllerJSProxy() in controller_preset_validation_test.o
      FakeControllerJSProxy::FakeControllerJSProxy() in controller_preset_validation_test.o
      FakeController::jsProxy() in controller_preset_validation_test.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
```

**Comment by ferranlala** [comment]
I managed to fix the issue by adding a header file to the test. I think the moc was not processing FakeControllerJSProxy. I'm pushing directly to https://github.com/mixxxdj/mixxx/pull/1795

**Pull request closed without merging**
