### PR TITLE
fix scripts for Qt 5.12

### PR DESCRIPTION
**Pull request by Be-ing**
and resolve merge conflict with master

### CODE REVIEW

**Comment by Be-ing** [comment]
@Swiftb0y are you able to test the changes to the Numark N4 script? This will require [building this PR with Qt 5.12](https://mixxx.org/wiki/doku.php/compiling_on_linux#non-system_qt).

**Comment by Be-ing** [comment]
Tests pass with Qt 5.12 :heavy_check_mark:

**Comment by Swiftb0y** [comment]
>  are you able to test the changes to the Numark N4 script?

Unfortunately not very soon. I don't have access to any of my controllers until the end of my christmas break (05.01.2019). However I can look over the modified code as well and do some manual testing by simulating controller interaction via a virtual device.

**Comment by Be-ing** [comment]
Don't worry, we can wait a few days.

**Review by ferranlala — CHANGES_REQUESTED** [review]
Cool. Thank you very much. Can we remove the lodash .js file then?

**Comment by Be-ing** [comment]
I did that in the last commit.

**Comment by ferranlala** [comment]
Its true, sorry. Thank you very much for this!

**Pull request merged**
