### PR TITLE
Skin layout revamp resolved conflicts 

### PR DESCRIPTION
**Pull request by daschuer**
Hi Ferran, 
I have merged your branch with master, and resolved conflicts.
Please merge, if I did it right. 
Thank you.

### CODE REVIEW

**Comment by ferranlala** [comment]
@daschuer Thank you very very much for keeping this up!

Also see my comment on https://github.com/mixxxdj/mixxx/pull/913

**Comment by ferranlala** [comment]
@daschuer shall we close this?

**Comment by daschuer** [comment]
Yes

**Comment by daschuer** [comment]
Hey, I have just used the close and comment button reasonable the first time.  :-P

**Pull request closed without merging**
