### PR TITLE
update Novation Launchpad controller scripts

### PR DESCRIPTION
**Pull request by dszakallas**
Updates Novation Launchpad sources and bundles to ~v2.2.3~ ~v2.2.4~ ~v2.2.5~ v2.2.6:

- Works with QJSEngine
  - [x] Qt 5.7 (on Debian Stretch)
  - [x] Qt 5.12 (on MacOS)

- Sends MIDI messages as numbers. Previously, strings were working fine, but on latest HEAD of the branch they are failing.

- Adds experimental support for Launchpad Pro. I don't have that controller, so I cannot guarantee it works properly until someone tests it.

- Contains a few bug fixes since 2.1.6

- Shrinks script size, which makes loading faster

See a better diff: https://github.com/dszakallas/mixxx-launchpad/compare/v2.1.6...v2.2.6

### CODE REVIEW

**Comment by Be-ing** [comment]
Great, thanks for working on this! Did you test with both Qt 5.12 and Qt < 5.12?

**Comment by Be-ing** [comment]
> Adds experimental support for Launchpad Pro. I don't have that controller, so I cannot guarantee it works properly until someone tests it.

I'd prefer to not ship the build for that with Mixxx until we have confirmation that it works from someone who has the hardware. Shipping a mapping with Mixxx should be an indicator that it does indeed work. If you want to post it to the forum instead, that would be great. If someone later posts that it does work with the hardware, we can ship it with Mixxx.

**Comment by dszakallas** [comment]
I only tested it with 5.12 so far.

**Comment by dszakallas** [comment]
> If someone later posts that it does work with the hardware, we can ship it with Mixxx.

OK, I'll do that. I'll remove the compiled script and MIDI mapping. I guess there's no harm leaving the sources as they are.

**Comment by Be-ing** [comment]
ping @ferranpujolcamins, can you merge this?

**Comment by ferranlala** [comment]
@dszakallas could you test in linux with Qt 5.9?

**Comment by dszakallas** [comment]
I can't, I need help with that

**Comment by dszakallas** [comment]
OK, I spun up a virtual machine and checked it, it doesn't work, because of that DataView/ByteArray issue discussed here: https://github.com/mixxxdj/mixxx/pull/1795#discussion_r252442190

**Comment by dszakallas** [comment]
I think this affects every version under Qt5.12

**Comment by dszakallas** [comment]
The bug is triggered when calling lodash's `isEqual`, so it will likely happen with other scripts using this function.

**Comment by dszakallas** [comment]
I removed the `lodash/isEquals` dependency, and tested on Qt 5.7.

**Comment by ferranlala** [comment]
@dszakallas  Thank you!

**Pull request merged**
